language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - python setup.py bdist_wheel --include-test-subpackage
  - pip install dist/feedgen*
  - rm -rf feedgen

script: make test
